# Generated by Django 5.2 on 2025-05-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
