# Generated by Django 5.2 on 2025-05-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_electionevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionevent',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='electionevent',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='electionevent',
            old_name='name',
            new_name='title',
        ),
    ]
