# Generated by Django 5.2 on 2025-05-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_rename_end_date_electionevent_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
