# Generated by Django 5.2 on 2025-05-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_position_event_alter_position_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.electionevent'),
        ),
    ]
