# Generated by Django 5.2 on 2025-05-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_controlvote_timestamp_alter_position_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionevent',
            name='eligible_voters',
            field=models.PositiveIntegerField(default=0, help_text='Number of eligible voters for this event'),
        ),
    ]
